apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app-cli
  name: python-app-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-cli
  template:
    metadata:
      labels:
        app: python-app-cli
    spec:
      #nodeSelector:
      #  lifecycle: Ec2Spot
      containers:
      - env:
        image: 163538056407.dkr.ecr.us-west-2.amazonaws.com/python-socket-psql-sample:0.1
        imagePullPolicy: Always
        name: python-socket-psql-sample
        command: ["/start-cli.sh"]
        resources:
          requests:
            cpu: 128m
            memory: 128Mi
